[package]
name = "vedirect"
version = "0.1.0"
authors = ["dbr <dbr.onix@gmail.com>"]
edition = "2018"
license = "Unlicense"
description = "Library to parse the Victron Energy VE.Direct protocol and map the data to useful structs with clear units"

[dependencies]
nom = "5.1"
thiserror = "1.0"

[dev-dependencies]
serial = "0.4"
anyhow = "1.0"
